name: WeaponsCore
main: ca.bungo.core.Core
authors: [Spaces, WhatATopic, Bungo, Nbarudi, Nick]
version: ${project.version}
depend: [Vault, WorldGuard, WorldEdit]
commands:
  getitems:
    description: Spawn custom weapons
    usage: /getitems